### ISSUE TITLE
Bruk av Java 8 features

### ISSUE THREAD

**Issue by FredrickB** [mesan/springKurs#1]
Bruk av Java 8 features som forEach() eller lignende i samsvar med oppgave 4 - Full Stack #8 (Oppretting av dummy data i PostConstruct metode) fører til mindre beskrivende feilmelding og kryptisk feilkode i stacktrace ved kjøring på Server.

**Comment by torbjornk** [comment]
Language level i pom var 1.7, bumpet til 1.8.
